# Dependencies
kramdown:
  syntax_highlighter_opts:
    disable : true

# Permalinks
permalink: /posts/:title/
timezone: Asia/Kolkata

exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  - README.md
  - LICENSE.md
  - .sass-cache
  - .travis.yml
  - .ruby-version
  - .gitignore

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

sass:
  sass_dir: _scss
  style: compressed

paginate: 5

# Custom vars
show_related_posts: false
show_social_icons: true


# please change ALL items bellow if you are forking my repo!
# you may also want to edit about.md and delete all posts and images.

title: Anuj Pahuja
description: 'Vision, Graphics and everything pixely.'
baseurl:     ''
google_analytics: UA-70927836-1
disqus_shortname: alasin
github_username: alasin
twitter_username: kmkzeanuj
linkedin_username: anujpahuja
email: anujpahuja13@gmail.com

author:
  name: 'Anuj Pahuja'
  email: anujpahuja13@gmail.com
  github: alasin
  twitter: kmkzeanuj
