# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: /posts/:title
timezone: Asia/Kolkata

# Setup
title: Anuj Pahuja
description: 'Just another dev blog.'
baseurl:     ''
url:         'http://alasin.github.io'

author:
  name: 'Anuj Pahuja'
  url: https://twitter.com/kmkzeanuj
  email: anujpahuja13@gmail.com

exclude:
  - Gemfile
  - Gemfile.lock
  - bin

gems:
  # - jekyll-mentions
  - jemoji
  - jekyll-redirect-from

sass:
  sass_dir: _scss
  compressed: true

paginate: 3

# Custom vars
show_related_posts: true
animated: true

# Social icons
show_social_icons: true
github_username: alasin
twitter_username: kmkzeanuj

google_analytics: UA-70927836-1
#disqus_shortname: caarlos0blog
